# Generated by Django 4.2.7 on 2025-11-15 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Botijao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_rfid', models.CharField(max_length=200, unique=True, verbose_name='Tag RFID')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número de Série')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('manutencao', 'Em Manutenção')], default='ativo', max_length=20, verbose_name='Status')),
                ('capacidade', models.DecimalField(blank=True, decimal_places=2, default=13.0, max_digits=5, null=True, verbose_name='Capacidade (kg)')),
                ('cliente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cliente')),
                ('localizacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Localização')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('fabricante', models.CharField(blank=True, help_text='Empresa fabricante do botijão', max_length=200, null=True, verbose_name='Fabricante')),
                ('tara', models.DecimalField(blank=True, decimal_places=3, help_text='Peso vazio do botijão em kg', max_digits=6, null=True, verbose_name='Tara (kg)')),
                ('data_ultima_requalificacao', models.DateField(blank=True, help_text='Data da última requalificação/inspeção', null=True, verbose_name='Última Requalificação')),
                ('data_proxima_requalificacao', models.DateField(blank=True, help_text='Data prevista para próxima requalificação (5 anos após última)', null=True, verbose_name='Próxima Requalificação')),
                ('status_requalificacao', models.CharField(choices=[('em_dia', 'Em Dia'), ('proximo_vencimento', 'Próximo ao Vencimento'), ('vencida', 'Vencida'), ('pendente', 'Pendente')], default='pendente', help_text='Situação atual da requalificação', max_length=30, verbose_name='Status Requalificação')),
                ('penultima_envasadora', models.CharField(blank=True, help_text='Empresa que envasou anteriormente', max_length=200, null=True, verbose_name='Penúltima Envasadora')),
                ('data_penultimo_envasamento', models.DateField(blank=True, null=True, verbose_name='Data Penúltimo Envasamento')),
                ('ultima_envasadora', models.CharField(blank=True, help_text='Empresa que envasou por último', max_length=200, null=True, verbose_name='Última Envasadora')),
                ('data_ultimo_envasamento', models.DateField(blank=True, null=True, verbose_name='Data Último Envasamento')),
                ('deletado', models.BooleanField(default=False, verbose_name='Deletado')),
                ('data_delecao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('deletado_por', models.CharField(blank=True, max_length=150, null=True, verbose_name='Deletado por')),
                ('motivo_delecao', models.TextField(blank=True, null=True, verbose_name='Motivo da Exclusão')),
            ],
            options={
                'verbose_name': 'Botijão',
                'verbose_name_plural': 'Botijões',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criar', 'Criar'), ('editar', 'Editar'), ('deletar', 'Deletar'), ('restaurar', 'Restaurar'), ('leitura', 'Leitura RFID')], max_length=20, verbose_name='Ação')),
                ('usuario', models.CharField(max_length=150, verbose_name='Usuário')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('dados_anteriores', models.JSONField(blank=True, null=True, verbose_name='Dados Anteriores')),
                ('dados_novos', models.JSONField(blank=True, null=True, verbose_name='Dados Novos')),
                ('botijao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_auditoria', to='rfid.botijao', verbose_name='Botijão')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='LeituraRFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('operador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operador')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('botijao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='rfid.botijao', verbose_name='Botijão')),
            ],
            options={
                'verbose_name': 'Leitura RFID',
                'verbose_name_plural': 'Leituras RFID',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='botijao',
            index=models.Index(fields=['tag_rfid'], name='rfid_botija_tag_rfi_72e4af_idx'),
        ),
        migrations.AddIndex(
            model_name='botijao',
            index=models.Index(fields=['numero_serie'], name='rfid_botija_numero__ba96f1_idx'),
        ),
        migrations.AddIndex(
            model_name='botijao',
            index=models.Index(fields=['status', 'deletado'], name='rfid_botija_status_5cd11d_idx'),
        ),
        migrations.AddIndex(
            model_name='botijao',
            index=models.Index(fields=['status_requalificacao'], name='rfid_botija_status__500033_idx'),
        ),
    ]
