# Generated by Django 4.2.7 on 2025-11-19 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Botijao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag_rfid",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Tag RFID"
                    ),
                ),
                (
                    "fabricante",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Fabricante"
                    ),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Número de Série",
                    ),
                ),
                (
                    "tara",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Tara (kg)",
                    ),
                ),
                (
                    "data_ultima_requalificacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Última Requalificação"
                    ),
                ),
                (
                    "data_proxima_requalificacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima Requalificação"
                    ),
                ),
                (
                    "penultima_envasadora",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Penúltima Envasadora",
                    ),
                ),
                (
                    "data_penultimo_envasamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Penúltimo Envasamento"
                    ),
                ),
                (
                    "ultima_envasadora",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Última Envasadora",
                    ),
                ),
                (
                    "data_ultimo_envasamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Último Envasamento"
                    ),
                ),
                ("deletado", models.BooleanField(default=False)),
                ("data_delecao", models.DateTimeField(blank=True, null=True)),
                ("motivo_delecao", models.TextField(blank=True, null=True)),
                (
                    "deletado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="botijoes_deletados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Botijão",
                "verbose_name_plural": "Botijões",
                "ordering": ["tag_rfid"],
            },
        ),
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("criar", "Criar"),
                            ("atualizar", "Atualizar"),
                            ("deletar", "Deletar"),
                            ("restaurar", "Restaurar"),
                            ("leitura", "Leitura RFID"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("descricao", models.TextField()),
                ("dados_anteriores", models.JSONField(blank=True, null=True)),
                ("dados_novos", models.JSONField(blank=True, null=True)),
                (
                    "botijao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="rfid.botijao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-data_hora"],
                "indexes": [
                    models.Index(
                        fields=["botijao", "-data_hora"],
                        name="rfid_logaud_botijao_9e7848_idx",
                    ),
                    models.Index(
                        fields=["acao", "-data_hora"],
                        name="rfid_logaud_acao_8f8cca_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeituraRFID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("operador", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "localizacao_leitura",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("observacao", models.TextField(blank=True, null=True)),
                ("rssi", models.IntegerField(blank=True, null=True)),
                ("antena", models.IntegerField(blank=True, null=True)),
                ("leitor_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "botijao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leituras",
                        to="rfid.botijao",
                        verbose_name="Botijão",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leitura RFID",
                "verbose_name_plural": "Leituras RFID",
                "ordering": ["-data_hora"],
                "indexes": [
                    models.Index(
                        fields=["botijao", "-data_hora"],
                        name="rfid_leitur_botijao_48cb20_idx",
                    ),
                    models.Index(
                        fields=["-data_hora"], name="rfid_leitur_data_ho_38e8af_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="botijao",
            index=models.Index(
                fields=["tag_rfid"], name="rfid_botija_tag_rfi_72e4af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="botijao",
            index=models.Index(
                fields=["numero_serie"], name="rfid_botija_numero__ba96f1_idx"
            ),
        ),
    ]
