# Generated by Django 4.2.7 on 2025-10-19 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Botijao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_rfid', models.CharField(max_length=100, unique=True, verbose_name='Tag RFID')),
                ('numero_serie', models.CharField(blank=True, help_text='Gerado automaticamente se não informado', max_length=50, unique=True, verbose_name='Número de Série')),
                ('capacidade', models.DecimalField(decimal_places=2, default=13.0, max_digits=5, verbose_name='Capacidade (kg)')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('manutencao', 'Em Manutenção')], default='ativo', max_length=20, verbose_name='Status')),
                ('cliente', models.CharField(blank=True, help_text='Nome do cliente ou empresa', max_length=200, null=True, verbose_name='Cliente')),
                ('localizacao', models.CharField(blank=True, help_text='Local físico onde o botijão se encontra', max_length=200, null=True, verbose_name='Localização Atual')),
                ('observacao', models.TextField(blank=True, help_text='Informações adicionais sobre o botijão', null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ultima_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Última Leitura')),
                ('deletado', models.BooleanField(default=False, verbose_name='Deletado')),
                ('data_delecao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão')),
                ('motivo_delecao', models.TextField(blank=True, null=True, verbose_name='Motivo da Exclusão')),
                ('deletado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='botijoes_deletados', to=settings.AUTH_USER_MODEL, verbose_name='Deletado por')),
            ],
            options={
                'verbose_name': 'Botijão',
                'verbose_name_plural': 'Botijões',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_relatorios', models.EmailField(blank=True, max_length=254, verbose_name='Email para Relatórios')),
                ('enviar_relatorio_diario', models.BooleanField(default=False, verbose_name='Enviar Relatório Diário')),
                ('alerta_dias_sem_leitura', models.IntegerField(default=30, verbose_name='Alerta - Dias sem Leitura')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criar', 'Criado'), ('editar', 'Editado'), ('deletar', 'Deletado'), ('restaurar', 'Restaurado'), ('leitura', 'Leitura RFID')], max_length=20, verbose_name='Ação')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('objeto_id', models.IntegerField(verbose_name='ID do Objeto')),
                ('objeto_repr', models.CharField(max_length=200, verbose_name='Representação do Objeto')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['-data_hora'], name='rfid_logaud_data_ho_ee0989_idx'), models.Index(fields=['modelo', 'objeto_id'], name='rfid_logaud_modelo_d5c377_idx')],
            },
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_rfid', models.CharField(db_index=True, max_length=50, verbose_name='Tag RFID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('operador', models.CharField(blank=True, max_length=100, verbose_name='Operador')),
                ('localizacao', models.CharField(blank=True, help_text='Local onde a leitura foi realizada', max_length=200, null=True, verbose_name='Localização')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('botijao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='rfid.botijao')),
            ],
            options={
                'verbose_name': 'Leitura',
                'verbose_name_plural': 'Leituras',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['-data_hora'], name='rfid_leitur_data_ho_2dc4d3_idx'), models.Index(fields=['tag_rfid'], name='rfid_leitur_tag_rfi_271c27_idx')],
            },
        ),
    ]
