# Generated by Django 4.2.7 on 2025-11-21 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfid", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="botijao",
            options={
                "ordering": ["-id"],
                "verbose_name": "Botijão",
                "verbose_name_plural": "Botijões",
            },
        ),
        migrations.AlterModelOptions(
            name="leiturarfid",
            options={"ordering": ["-data_hora"]},
        ),
        migrations.AlterModelOptions(
            name="logauditoria",
            options={"ordering": ["-data_hora"]},
        ),
        migrations.RemoveIndex(
            model_name="leiturarfid",
            name="rfid_leitur_botijao_48cb20_idx",
        ),
        migrations.RemoveIndex(
            model_name="leiturarfid",
            name="rfid_leitur_data_ho_38e8af_idx",
        ),
        migrations.RemoveIndex(
            model_name="logauditoria",
            name="rfid_logaud_botijao_9e7848_idx",
        ),
        migrations.RemoveIndex(
            model_name="logauditoria",
            name="rfid_logaud_acao_8f8cca_idx",
        ),
        migrations.RemoveField(
            model_name="leiturarfid",
            name="localizacao_leitura",
        ),
        migrations.AddField(
            model_name="botijao",
            name="status",
            field=models.CharField(
                choices=[
                    ("ativo", "Ativo"),
                    ("inativo", "Inativo"),
                    ("manutencao", "Manutenção"),
                ],
                default="ativo",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="botijao",
            name="status_requalificacao",
            field=models.CharField(
                choices=[
                    ("em_dia", "Em Dia"),
                    ("proximo_vencimento", "Próximo ao Vencimento"),
                    ("vencida", "Vencida"),
                    ("pendente", "Pendente"),
                ],
                default="pendente",
                max_length=20,
                verbose_name="Status da Requalificação",
            ),
        ),
        migrations.AddField(
            model_name="botijao",
            name="total_leituras",
            field=models.IntegerField(default=0, verbose_name="Total de Leituras"),
        ),
        migrations.AlterField(
            model_name="botijao",
            name="data_penultimo_envasamento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Penúltimo Envasamento"
            ),
        ),
        migrations.AlterField(
            model_name="botijao",
            name="data_ultimo_envasamento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Último Envasamento"
            ),
        ),
        migrations.AlterField(
            model_name="botijao",
            name="numero_serie",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Número de Série"
            ),
        ),
        migrations.AlterField(
            model_name="leiturarfid",
            name="botijao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leituras",
                to="rfid.botijao",
            ),
        ),
        migrations.AddIndex(
            model_name="botijao",
            index=models.Index(fields=["status"], name="rfid_botija_status_c71fce_idx"),
        ),
    ]
