# Generated by Django 4.2.7 on 2025-11-18 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='botijao',
            name='rfid_botija_status__500033_idx',
        ),
        migrations.RemoveField(
            model_name='botijao',
            name='data_penultimo_envasamento',
        ),
        migrations.RemoveField(
            model_name='botijao',
            name='data_ultimo_envasamento',
        ),
        migrations.RemoveField(
            model_name='botijao',
            name='penultima_envasadora',
        ),
        migrations.RemoveField(
            model_name='botijao',
            name='tara',
        ),
        migrations.RemoveField(
            model_name='botijao',
            name='ultima_envasadora',
        ),
        migrations.AddField(
            model_name='botijao',
            name='ano_fabricacao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Fabricação'),
        ),
        migrations.AddField(
            model_name='botijao',
            name='certificado_inmetro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Certificado INMETRO'),
        ),
        migrations.AddField(
            model_name='botijao',
            name='lote_fabricacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote de Fabricação'),
        ),
        migrations.AddField(
            model_name='botijao',
            name='peso_cheio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso do botijão cheio', max_digits=6, null=True, verbose_name='Peso Cheio (kg)'),
        ),
        migrations.AddField(
            model_name='botijao',
            name='peso_vazio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso do botijão vazio (tara)', max_digits=6, null=True, verbose_name='Peso Vazio (kg)'),
        ),
        migrations.AddField(
            model_name='botijao',
            name='pressao_teste',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pressão de teste hidrostático', max_digits=6, null=True, verbose_name='Pressão de Teste (bar)'),
        ),
        migrations.AddField(
            model_name='botijao',
            name='total_enchimentos',
            field=models.IntegerField(default=0, help_text='Número de vezes que foi enchido', verbose_name='Total de Enchimentos'),
        ),
        migrations.AddField(
            model_name='botijao',
            name='total_km_percorridos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimativa de distância percorrida', max_digits=10, verbose_name='KM Percorridos'),
        ),
        migrations.AddField(
            model_name='botijao',
            name='total_leituras',
            field=models.IntegerField(default=0, help_text='Contador automático de leituras', verbose_name='Total de Leituras'),
        ),
        migrations.AddField(
            model_name='leiturarfid',
            name='antena',
            field=models.IntegerField(blank=True, help_text='Número da antena que fez a leitura', null=True, verbose_name='Antena'),
        ),
        migrations.AddField(
            model_name='leiturarfid',
            name='leitor_id',
            field=models.CharField(blank=True, help_text='Identificador do dispositivo leitor', max_length=100, null=True, verbose_name='ID do Leitor'),
        ),
        migrations.AddField(
            model_name='leiturarfid',
            name='localizacao_leitura',
            field=models.CharField(blank=True, help_text='Local onde foi feita a leitura', max_length=200, null=True, verbose_name='Localização da Leitura'),
        ),
        migrations.AddField(
            model_name='leiturarfid',
            name='rssi',
            field=models.IntegerField(blank=True, help_text='Força do sinal RFID', null=True, verbose_name='RSSI'),
        ),
        migrations.AlterField(
            model_name='botijao',
            name='capacidade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidade em kg (ex: 13.00, 20.00, 45.00)', max_digits=5, null=True, verbose_name='Capacidade (kg)'),
        ),
        migrations.AlterField(
            model_name='botijao',
            name='cliente',
            field=models.CharField(blank=True, help_text='Nome do cliente ou empresa', max_length=200, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='botijao',
            name='data_proxima_requalificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Requalificação'),
        ),
        migrations.AlterField(
            model_name='botijao',
            name='data_ultima_requalificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Última Requalificação'),
        ),
        migrations.AlterField(
            model_name='botijao',
            name='deletado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='botijoes_deletados', to=settings.AUTH_USER_MODEL, verbose_name='Deletado por'),
        ),
        migrations.AlterField(
            model_name='botijao',
            name='fabricante',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='botijao',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Endereço ou localização atual do botijão', max_length=200, null=True, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='botijao',
            name='numero_serie',
            field=models.CharField(blank=True, help_text='Número de série do botijão (informar manualmente)', max_length=100, null=True, unique=True, verbose_name='Número de Série'),
        ),
        migrations.AlterField(
            model_name='botijao',
            name='observacao',
            field=models.TextField(blank=True, help_text='Informações adicionais sobre o botijão', null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='botijao',
            name='status_requalificacao',
            field=models.CharField(choices=[('em_dia', 'Em Dia'), ('proximo_vencimento', 'Próximo ao Vencimento'), ('vencida', 'Vencida'), ('pendente', 'Pendente')], default='pendente', max_length=20, verbose_name='Status Requalificação'),
        ),
        migrations.AlterField(
            model_name='botijao',
            name='tag_rfid',
            field=models.CharField(help_text='Código único da tag RFID', max_length=200, unique=True, verbose_name='Tag RFID'),
        ),
        migrations.AlterField(
            model_name='leiturarfid',
            name='botijao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='rfid.botijao', verbose_name='Botijão'),
        ),
        migrations.AlterField(
            model_name='leiturarfid',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Leitura'),
        ),
        migrations.AlterField(
            model_name='leiturarfid',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observações sobre esta leitura específica', null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='leiturarfid',
            name='operador',
            field=models.CharField(blank=True, help_text='Nome do operador que fez a leitura', max_length=100, null=True, verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(choices=[('criar', 'Criar'), ('atualizar', 'Atualizar'), ('deletar', 'Deletar'), ('restaurar', 'Restaurar'), ('leitura', 'Leitura RFID')], max_length=20, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='botijao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rfid.botijao', verbose_name='Botijão'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='dados_anteriores',
            field=models.JSONField(blank=True, help_text='Estado anterior do objeto (JSON)', null=True, verbose_name='Dados Anteriores'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='dados_novos',
            field=models.JSONField(blank=True, help_text='Novo estado do objeto (JSON)', null=True, verbose_name='Dados Novos'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='botijao',
            index=models.Index(fields=['data_proxima_requalificacao'], name='rfid_botija_data_pr_a79959_idx'),
        ),
        migrations.AddIndex(
            model_name='leiturarfid',
            index=models.Index(fields=['botijao', '-data_hora'], name='rfid_leitur_botijao_48cb20_idx'),
        ),
        migrations.AddIndex(
            model_name='leiturarfid',
            index=models.Index(fields=['-data_hora'], name='rfid_leitur_data_ho_38e8af_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['botijao', '-data_hora'], name='rfid_logaud_botijao_9e7848_idx'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['acao', '-data_hora'], name='rfid_logaud_acao_8f8cca_idx'),
        ),
    ]
