# Generated by Django 4.2.7 on 2025-11-22 01:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfid", "0002_alter_botijao_options_alter_leiturarfid_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botijao",
            name="data_cadastro",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Data de Cadastro",
            ),
            preserve_default=False,
        ),
    ]
