# Generated by Django 4.2.7 on 2025-11-26 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfid', '0003_botijao_data_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoXLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_nome', models.CharField(max_length=300)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('total_linhas', models.IntegerField(default=0)),
                ('leituras_importadas', models.IntegerField(default=0)),
                ('novos_botijoes', models.IntegerField(default=0)),
                ('duplicados_ignorados', models.IntegerField(default=0)),
                ('erros', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
