# Generated by Django 4.2.7 on 2025-11-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfid", "0004_importacaoxls"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeituraCodigoBarra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=200)),
                (
                    "origem",
                    models.CharField(
                        default="PDA",
                        help_text="Origem da leitura (PDA, manual, outro).",
                        max_length=50,
                    ),
                ),
                ("operador", models.CharField(blank=True, max_length=100, null=True)),
                ("observacao", models.TextField(blank=True, null=True)),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-data_hora"],
            },
        ),
    ]
