# Generated by Django 4.2.7 on 2026-01-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rfid", "0005_leituracodigobarra"),
    ]

    operations = [
        migrations.AddField(
            model_name="botijao",
            name="indice_distribuidora",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Controle interno do ciclo de distribuidoras (0..3). NULL = não iniciado.",
                null=True,
                verbose_name="Índice Distribuidora (0-3)",
            ),
        ),
    ]
